### ISSUE TITLE
Windows下的一些问题

### ISSUE THREAD

**Issue by pandaiiz** [dongyuanxin/cloudpress#17]
1. 需要提前安装一下@cloudbase/cli 和 next
> $ npm i -g @cloudbase/cli next

2. 三个脚本都运行失败了，修改了一下兼容Windows下的git操作

>  "scripts": {
        "commit": "git-cz",
        "init:db": "node ./bin/init-db",
        "login": "sh ./bin/login.sh",
        "deploy:frontend": "sh ./bin/deploy-frontend.sh",
        "zip:service": "cd service/ && zip service.zip -r ./ -x node_modules/\\* dist/\\* test/\\* && cd -"
    },

3. frontend下运行npm start想本地调试，服务跑不起来

**Comment by pandaiiz** [comment]
待会提个pr修改一下

**Comment by dongyuanxin** [comment]
#18 Fixed
